AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello world lambda with api gateway integration

Resources:
  HelloWorldFunc:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Timeout: 10
      MemorySize: 128
      CodeUri: src
      Handler: hello_world.lambda_handler
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  ApiEndpoint:
    Description: Our hello world api-endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"