AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello wordl lambda with api gateway integration

Resources:
  GetCurrentConfig:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Timeout: 10
      MemorySize: 128
      CodeUri: src
      Handler: hello_world.lambda_handler
      Events:
        SetResource:
          Type: Api
          Properties:
            Path: /hello
            Method: get