AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GalCloud upboard server remote code updater service

Resources:
  GetCurrentConfig:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Timeout: 10
      MemorySize: 128
      CodeUri: src
      Handler: hello_world.lambda_handler